let word_all = [
    ['ant', 'allow', 'apple'],
    ['bird', 'born', 'box'],
    ['cat', 'cause', 'cool'],
    ['dog', 'done', 'draw'],
    ['egg', 'event', 'ever'],
    ['fish', 'for', 'fun'],
    ['gost', 'gone', 'gull'],
    ['house', 'hall', 'horse'],
    ['ice', 'inner', 'idea'],
    ['jar', 'june', 'just'],
    ['knite', 'korea', 'keep'],
    ['lion', 'lead', 'land'],
    ['monkey', 'mounth', 'manual'],
    ['neck', 'new', 'none'],
    ['owl', 'open', 'outdoor'],
    ['pen', 'pencil', 'pork'],
    ['quake', 'qeen', 'queue'],
    ['run', 'roll', 'road'],
    ['sport', 'support', 'sand'],
    ['two', 'temple', 'touch'],
    ['unuse', 'under', 'unity'],
    ['van', 'valley', 'value'],
    ['went', 'win', 'walk'],
    ['xmas', 'xenon', 'xerox'],
    ['yes', 'you', 'young'],
    ['zebra', 'zeal', 'zone'],
]